services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5173:5173"
      - "0.0.0.0:3001:3001"
    environment:
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
